name: Build Frame Snap

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.29.2

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
        # os: [ ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: astral-sh/setup-uv@v5
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Flutter Doctor
        run: |
          flutter config --no-cli-animations
          flutter doctor -v

      - name: Get packages
        run: |
          flutter pub get

      - name: Build Flutter
        run: |
          flutter build linux --release
